### ISSUE TITLE
Brainstorming for Brigade Congress

### ISSUE THREAD

**Issue by gregboyer** [codeforamerica/brigade-project-index#14]
Brigade Congress is coming up and CfA is soliciting content suggestions. What ideas do you have for using Congress as an opportunity for community involvement in this project?

**Comment by themightychris** [comment]
Let's try to have something together that puts tagged projects into some useful national context so our event for brigade congress could be an "index your brigade" workshop where brigade organizers sit and go through some of their actual brigade projects, try out tagging them with metadata (taxonomy tags?), and actually see their labors result in their brigade's projects showing up somewhere useful.

This would be a great chance to get early feedback on the index dynamics and kick-start a data set

**Comment by nikolajbaer** [comment]
It could be cool to have an interactive d3 type explorer microsite where brigades can see their projects and the meta-data (or lack thereof) per project. Maybe a progress-bar to show how far they are from being totally indexed.

The analysis code I have is kind of a start to this (in terms of data gathering), so I am ok with maybe pursuing this a bit further to build an explorable data-viz of brigade project meta-data.

**Comment by ExperimentsInHonesty** [comment]
### Overview
We need to market this project, so that every brigade leader leaves with the exciting news that their brigade is going to be connected to every other brigade through this Index as well as to the people who come to CFA but don't want to surf every brigade website to find all projects about X, or that use X, or have the status of X, or need X.

### How we do this
We present a killer **slide deck** based on the user stories that will be in the MVP, and present our **educational materials** that we will have developed, that will help people ~~adopt it~~ join the party.

### Details
_Where X equals the meta data fields we decide on (potential fields):_
_- Topics_ 
_- Technologies_
_- Project Stage_
_- Project Status_
_- Project Roles_
_- Skills Needed_

**Comment by ckingbailey** [comment]
Is it possible to combine all three of these ideas? I'm picturing a workshop flow like this:
- Brigade members enter: we provide them with educational materials we have developed
- The work of the workshop: "index your projects", per @themightychris above
- Wrap up: use @nikolajbaer 's tool to visual the work we've done in this workshop, as a group briefly gloss what's to be learned from visualization
- On exit: provide participants with a URL to mobile-ready site displaying results of workshop, and/or printed material, so that they can show off this hot new thing to their pals who are also brigade leaders or proactive brigade members

**Comment by gregboyer** [comment]
Colin, seems like that workflow would tie it together nicely, and give us the energy to start adoption.

It’s hard to predict how much we’ll have complete by Congress, so some things could shift on the hands on exercises, but that aside, I think having portions for 1) education 2) hands on 3) takeaways / call to action is perfect

Greg

**Comment by gregboyer** [comment]
Proposal for Brigade Congress:

The Brigade Project Index is a team of 7 different brigades collaborating on an index of current and past projects generated across the brigade network. At Congress, the team would like to lead an hour-long session on transparency and visibility of volunteer projects throughout the network. This session would include 1) A presentation of the work to date, and educational materials on how to leverage it 2) A workshop where participants would actively use the index, including adding projects to the index, and 3) take aways including how they can participate and get their brigades involved in the project [including visualizations as a selling point].

How does that sound?
