### ISSUE TITLE
Analysis of adoption of civic.json amongst brigades / metrics

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index#3]

**Comment by nikolajbaer** [comment]
Some initial stats that I have:

6,475 projects over 207 brigades from the CFAPI where type="Brigade, Code for America, Official"
98% of these projects are hosted on github
114 (1.76%) have a "civic.json" file
of these, only 8 were valid by the "Extended" civicjson validator from Code for DC

The most frequent validation errors were:

104 times: 'name' is a required property
14 times: 'Official' is not one of ['Ideation', 'Alpha', 'Beta', 'Production', 'Archival']
13 times: 'Experiment' is not one of ['Ideation', 'Alpha', 'Beta', 'Production', 'Archival']
8 times: 'In Progress' is not one of ['Ideation', 'Alpha', 'Beta', 'Production', 'Archival']
(note: the last 3 are in regards to the status field)

I have a list of questions I am looking to answer for my own curiosity, but please feel free to suggest further questions. The first two questions I now have answers for:

- [ ] What % of projects / brigades are using Civic.json?
- [ ] How many are using the Code for DC Extended version?
- [ ] What is the spread of status vs age of last commit ( e.g. how many are "Archived" vs just out of date)
- [ ] How many have a working production url / project URL?
- [ ] How many are using tags? What are the most common tags?
- [ ] Bonus: can we identify forks? Is there a visible level of duplication?

**Comment by themightychris** [comment]
@nikolajbaer awesome analysis!

Re: forks, I haven't seen anything in `civic.json` yet that offered a good way to track forks, and I'm pessimistic that we could glean quality data automatically.

The related [`publiccode.yml`](https://github.com/italia/publiccode.yml) standard has an [`isBasedOn`](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/schema.core.html#key-isbasedon) key for linking to repository that the project is a "variant or fork" of

Re: adoption, what conclusions are folks looking to draw from the adoption metrics? My own sense is that no one is going to implement a standard just because it's a standard. Rather, adoption will be driven by the value of what implementing the standard gets you. So I suggest that adoption statistics don't teach us much about `civic.json` itself but rather just the marginal utility over having a project with no metadata indexed in the [current crop of CfAPI tools](https://github.com/codeforamerica/cfapi#projects-powered-by-the-cfapi)

**Comment by nikolajbaer** [comment]
@themightychris thanks

As far as adoption goes, I think I am more just trying to understand if civic.json (or other metadata) is common (it clearly isn't, or maybe it is on only active, popular projects?), and how representative it is of actual brigade project activity.

A possible benefit of knowing that there isn't that much use of an already accessible and implemented standard, is that we can probably mobilize brigades to all jam out civic.json updates for their projects, and get a big improvement in the quality of the current brigade projects, with a minimum of effort on the part of brigades. The "carrot" could be an improved listing format on a new Brigade Project Index. The model for this is the push by Google for schema.org adoption, and other improved metadata. An additional "stick" might be a quarterly update to brigade captains when they have validation issues or missing metadata on projects (also an opportunity for brigades to engage with the broader network).

**Comment by themightychris** [comment]
@nikolajbaer great points

Another thing I just realized, this analysis is very helpful for reviewing the impact of any changes/additions we might want to make to `civic.json` -- looks like we have a pretty green field in that regard

Could you share some of the code you used for your analysis in a gist?

**Comment by nikolajbaer** [comment]
Ok, I pushed up the script I have been writing to a branch called "analysis", in the scripts folder.

It requires python3 and a few dependencies in the requirements.txt. It also relies a lot on  requests caching library, as the first run is pretty heavy on the cfapi and chews up the github access token rate limit (you will probably need to run it twice to get it fully cached).

https://github.com/codeforamerica/brigade-project-index/tree/analysis/scripts

**Comment by gregboyer** [comment]
Anything more before closing this?

**Comment by nikolajbaer** [comment]
I have a few more things I wanted to do, but I think the goal of this issue is achieved. I will close.
